name: Ansible CI

on: 
  pull_request:

  push:
    branches:
      - main

# Prevents concurrent runs of the same workflow
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    name: Run ansible lint
    uses: exzeo-devops/action-workflows/.github/workflows/ansible-lint.yaml@fc470cd62a87df6c2a8ce2189e0d9656551dd9a0 # v1.0.3
    secrets: inherit

  test:
    name: Run ansible CI

    # Needs to run after the lint job
    needs: [lint]

    # Example of a matrix
    strategy:
      matrix:
        include:
          - scenario: default
            image: ubuntu-2404-ansible
          - scenario: default
            image: ubuntu-2204-ansible
          - scenario: default
            image: ubuntu-2004-ansible
          - scenario: specific-version
            image: ubuntu-2404-ansible
          - scenario: specific-version
            image: ubuntu-2204-ansible
          - scenario: specific-version
            image: ubuntu-2004-ansible

    uses: exzeo-devops/action-workflows/.github/workflows/ansible-test.yaml@fc470cd62a87df6c2a8ce2189e0d9656551dd9a0 # v1.0.3
    secrets: inherit
    with:
      scenario: ${{ matrix.scenario }}
      image: ${{ matrix.image }}