name: Create new release

on:
  # Allow for manual triggers
  workflow_dispatch:

  # Allow pushes to main to trigger
  push:
    branches:
      - main

# Sets up concurrency to ensure that only one job or workflow using the same concurrency group will run at a time.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  release:
    name: Create new release
    uses: exzeo-devops/action-workflows/.github/workflows/create-release.yaml@77f09e3768eb6207d8c6cba1ea14b1186ce9b944 # v1.0.4
    secrets: inherit
