name: Build docker image

on:
  # Trigger on all pull request events
  pull_request:

  # Trigger when tag is pushed
  push:
    tags:
      - 'v*'

# Sets up concurrency to ensure that only one job or workflow using the same concurrency group will run at a time.
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: Build docker image
    uses: exzeo-devops/action-workflows/.github/workflows/docker-build.yaml@743a2bae5dac57cb68d82030ddec14a32481115f # v1.0.0
    secrets: inherit