name: Build docker image

on:
  # Trigger on all pull request events
  pull_request:

  # Trigger when tag is pushed
  push:
    tags:
      - 'v*'

# Sets up concurrency to ensure that only one job or workflow using the same concurrency group will run at a time.
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: Build docker image
    uses: exzeo-devops/action-workflows/.github/workflows/docker-build.yaml@fc470cd62a87df6c2a8ce2189e0d9656551dd9a0 # v1.0.3
    secrets: inherit