name: Golang CI

on:
  # Ensure build works in a pull request
  pull_request:

  # Allow pushes to main to trigger
  push:
    branches:
      - main

# Sets up concurrency to ensure that only one job or workflow using the same concurrency group will run at a time.
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  ci:
    name: "Run golang ci"
    uses: exzeo-devops/action-workflows/.github/workflows/golang-ci.yaml@77f09e3768eb6207d8c6cba1ea14b1186ce9b944 # v1.0.4
    secrets: inherit