name: Helm Publish

on:
  # Allow manual trigger
  workflow_dispatch:

  # Ensure build works in a pull request
  pull_request:
    branches: [ $default-branch ]
    types: [ closed ]
    paths:
      - "charts/**"

# Sets up concurrency to ensure that only one job or workflow using the same concurrency group will run at a time.
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  publish:
    name: Publish helm charts

    # Only run the job on the default branch
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}

    # Specify the job to run on the latest Ubuntu version
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          path: src
          ref: $default-branch

      # https://github.com/actions/checkout
      - name: Checkout gh-pages
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          path: dest
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: gh-pages

      # https://github.com/azure/setup-helm
      - name: Install Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0

      # https://github.com/docker/login-action
      - name: Login to GHCR
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package helm charts
        working-directory: src
        id: package
        run: |
          for chart_dir in ./charts/*; do
            if [ -f "$chart_dir/Chart.yaml" ]; then
              chart_name=$(basename "$chart_dir")
              version=$(helm show chart $chart_dir | yq '.version')              
              dest_file="../dest/$chart_name-$version.tgz"
              if [ ! -f "$dest_file" ]; then
                helm package $chart_dir --destination ../dest --dependency-update
                echo "Packaged $chart_name $version into $dest_file"
                echo "new_chart_added=true" >> $GITHUB_OUTPUT
              fi
            fi
          done

      - name: Upload new helm charts
        working-directory: dest
        if: ${{ steps.package.outputs.new_chart_added == 'true' }}
        run: |
          helm repo index . --merge ./index.yaml --url https://raw.githubusercontent.com/${{ github.repository }}/gh-pages/          
          if ! git diff-index --quiet HEAD --; then
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add .
            git commit -m "Publish helm charts"
            git push
          fi