name: Helm Publish

on:
  # Allow manual trigger
  workflow_dispatch:

  # Ensure build works in a pull request
  pull_request:
    types: [ closed ]
    paths:
      - "charts/**"

# Sets up concurrency to ensure that only one job or workflow using the same concurrency group will run at a time.
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  publish:
    name: Publish helm charts

    # Only run the job on the default branch
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}

    uses: exzeo-devops/action-workflows/.github/workflows/helm-publish.yaml@743a2bae5dac57cb68d82030ddec14a32481115f # v1.0.0
    secrets: inherit