name: Helm CI

on:
  # Ensure build works in a pull request
  pull_request:
    paths:
      - "charts/**"

# Sets up concurrency to ensure that only one job or workflow using the same concurrency group will run at a time.
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  helm:
    name: "Run helm ci"
    uses: exzeo-devops/action-workflows/.github/workflows/helm-ci.yaml@ed38ca716c82f1c030ce20f2d5622c6b2b1e35b7 # v1.0.2
    secrets: inherit