name: Auto-merge dependabot

on:
  # Allow trigger on pull request
  pull_request:

# Sets up concurrency to ensure that only one job or workflow using the same concurrency group will run at a time.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  dependabot:
    name: Auto-merge dependabot

    # Specify the job to run on the latest Ubuntu version
    runs-on: ubuntu-latest

    # Only run this job if the actor is dependabot
    if: github.actor == 'dependabot[bot]'

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      # https://github.com/actions/create-github-app-token
      - name: Get Token
        id: app-token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        with:
          app-id: "872585"
          private-key: ${{ secrets.GIT_AUTOMATION_PK }}

      # https://github.com/dependabot/fetch-metadata
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34 # v2.2.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}

      # https://github.com/actions/github-script
      - name: Approve the pull request
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        if: (steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor')
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const pullRequestId = context.payload.pull_request.node_id;

            await github.graphql(`
              mutation($pullRequestId: ID!) {
                addPullRequestReview(input: {
                  pullRequestId: $pullRequestId,
                  event: APPROVE
                }) {
                  pullRequestReview {
                    id
                    state
                  }
                }
              }
            `, {
              pullRequestId: pullRequestId
            });

      # https://github.com/actions/github-script
      - name: Merge the Pull Request
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        if: (steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor')
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const pullRequestId = context.payload.pull_request.node_id;

            await github.graphql(`
              mutation($pullRequestId: ID!, $mergeMethod: PullRequestMergeMethod!) {
                mergePullRequest(input: {
                  pullRequestId: $pullRequestId,
                  mergeMethod: $mergeMethod
                }) {
                  pullRequest {
                    merged
                    mergeCommit {
                      oid
                    }
                  }
                }
              }
            `, {
              pullRequestId: pullRequestId,
              mergeMethod: 'SQUASH'  // You can also use 'MERGE' or 'REBASE'
            });          