name: NodeJS CI

on:
  # Ensure build works in a pull request
  pull_request:
    branches: [ main ]

  # Allow pushes to main to trigger
  push:
    branches: [ main ]

# Sets up concurrency to ensure that only one job or workflow using the same concurrency group will run at a time.
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  node-security:
    name: "NPM Audit"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*

      - name: Run NPM Audit
        uses: oke-py/npm-audit-action@2c6b2da234031fbf72af81a04c76b3a152bb2222 # v2.4.4
        with:
          audit_level: "moderate"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_issues: false
          create_pr_comments: true

  codeql:
    name: Scan code using codeql

    # Specify the job to run on the latest Ubuntu version
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/actions/create-github-app-token
      - name: Get Token
        id: app-token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        with:
          app-id: ${{ secrets.GIT_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.GIT_AUTOMATION_PK }}

      # https://github.com/github/codeql-action
      - name: Initialize CodeQL
        uses: github/codeql-action/init@40e16edda1c08370bd06454cc0d3b0d4270d7c75 # v3.26.6
        with:
          languages: javascript
          token: ${{ steps.app-token.outputs.token }}

      # https://github.com/github/codeql-action
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@40e16edda1c08370bd06454cc0d3b0d4270d7c75 # v3.26.6

  node-tests:
    name: "Runs unit tests"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
      
      - name: Run Tests
        run: |
          if make -n test >/dev/null 2>&1; then
            make test
          else
            npm test
          fi
