name: Terraform CI

on:
  pull_request:

  # Allow pushes to main to trigger
  push:
    branches:
      - main

# Sets up concurrency to ensure that only one job or workflow using the same concurrency group will run at a time.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  terraform-ci:
    name: Terraform CI
    uses: exzeo-devops/action-workflows/.github/workflows/terraform-ci.yaml@ed38ca716c82f1c030ce20f2d5622c6b2b1e35b7 # v1.0.2
    secrets: inherit